### PR TITLE
Fixes d-krupke/slurminade#8

### PR DESCRIPTION
**Pull request by p-blumenberg**
Added call to dispatch_guard in Dispatcher.
Added tests for dispatch limit with and without batches.

### CODE REVIEW

**Comment by p-blumenberg** [comment]
Should calls to sbatch and srun also be counted?

**Comment by d-krupke** [comment]
Yes. They also create slurm tasks that in case of a bug could overload slurm.

**Comment by p-blumenberg** [comment]
We call dispatch_guard from every Dispatcher subclass now because there was no straightforward way to do this in the parent class without breaking anything.
Let me know if you want me to implement a more maintainable solution.

**Comment by d-krupke** [comment]
Looks good! I don't see a much better way to do it right now. It is not beautiful but as long as it is this simple, I don't think we need a more maintainable solution. Better to continue on the problem with too long calls with batches (the thing with the temp file solution). :thinking: 
Could you please bump up the version number (last number because it is a bugfix) and add an entry to the changelog? I will then merge it and trigger the distribution.

**Pull request merged**
